test_that("OWL satisfies tbl methods for completion.", {
    o <- OWL()
    expect_identical( dimnames(o), list("term", character(0)) )
    expect_identical( dim(o), lengths(list("term", character(0))) )
    expect_identical( length(o), length(character(0)))
    expect_identical(o, o[])
    expect_error(o[[]], "missing subscript")
    expect_error(o[1L,"I don't exist"], "subscript out of bounds")
    expect_null(o["I don't exist"])
    expect_identical(o$somewhere, o["somewhere"])
})
