test_that("OWL_env satisfies tbl methods for completion.", {
    e <- OWL_env(list(p = paste, p0 = paste0))
    expect_identical( dimnames(e), list("term", c("p", "p0")) )
    expect_identical( dim(e), lengths(list("term", c("p", "p0"))) )
    expect_identical( length(e), 2L)
    expect_identical(e, e[])
    expect_error(e[[]], "missing subscript")
    expect_no_error(e[1L,"ignore_me"])
    expect_null(e["dont_ignore_me"])
    expect_identical(e$p, e["p"])
    expect_identical(e$p0, e["p0"])
})
